name: image-build
on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
      aws_region:
        required: true
      docker_build_dir:
        required: true
      image_tag:
        required: true
      ecr_repoistory:
        required: true

jobs:
  image-build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    env:
      AWS_ACCOUNT_ID: ${{ inputs.aws_account_id }}
      AWS_REGION: ${{ inputs.aws_region }}
      DOCKER_BUILD_DIR: ${{ inputs.docker_build_dir }}
      IMAGE_TAG: ${{ inputs.image_tag }}
      ECR_REPOSITORY: ${{ inputs.ecr_repoistory }}

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::$AWS_ACCOUNT_ID:role/GitHubActionsRole
          aws-region: $AWS_REGION

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registries: $AWS_ACCOUNT_ID

      - name: Build, tag, and push image to Amazon ECR
        id: build-publish
        shell: bash
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build $DOCKER_BUILD_DIR -f $DOCKER_BUILD_DIR/Dockerfile -t "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          docker push "$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
          echo "IMAGE $IMAGE_TAG is pushed to $ECR_REGISTRY/$ECR_REPOSITORY"
          echo "full_image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
