name: update-lambda

on:
  workflow_call:
    inputs:
      aws_account_id:
        required: true
        type: string
      aws_region:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      lambda_function_name:
        required: true
        type: string

jobs:
  update-lambda:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ inputs.aws_account_id }}:role/GitHubActionsRole
          aws-region: ${{ inputs.aws_region }}

      - name: Update AWS Lambda with new image
        env:
          ECR_IMAGE_URI: "015059194123.dkr.ecr.us-east-1.amazonaws.com/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}"
        run: |
          sleep 30
          aws lambda update-function-code \
            --function-name ${{ inputs.lambda_function_name }} \
            --image-uri $ECR_IMAGE_URI
