name: memcached-testing

on:
  push:
    paths:
      - "api-gw-nat/**"
      - "cron/**"

jobs:
  api-gw-nat-image:
    uses: ./.github/workflows/image-build.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      docker_build_dir: "api-gw-nat/image"
      image_tag: "latest"
      ecr_repository: "personal/api_gw_nat"

    permissions:
      id-token: write
      contents: read


  cron-image:
    uses: ./.github/workflows/image-build.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      docker_build_dir: "cron/image"
      image_tag: "latest"
      ecr_repository: "personal/cron"

    permissions:
      id-token: write
      contents: read


  update-api-gw-nat-lambda:
    needs: api-gw-nat-image

    uses: ./.github/workflows/update-lambda.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      image_tag: "latest"
      lambda_function_name: "api_gw_nat"

    permissions:
      id-token: write
      contents: read


  update-cron-lambda:
    needs: cron-image

    uses: ./.github/workflows/update-lambda.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      image_tag: "latest"
      lambda_function_name: "cron"

    permissions:
      id-token: write
      contents: read
