name: memcached-testing

on: [push]

# concurrency required to avoid terraform lock contention during ECR provisioning
concurrency: ci-${{ github.repository }}-docker-pipeline

jobs:
  stock-image:
    uses: ./.github/workflows/image-build.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      docker_build_dir: "stock/image"
      image_tag: "stock"
      ecr_repository: "personal/test"

    permissions:
      id-token: write
      contents: read

  third-party-api-sync-image:
    uses: ./.github/workflows/image-build.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      docker_build_dir: "third-party-sync/image"
      image_tag: "third-party-sync"
      ecr_repository: "personal/test"

    permissions:
      id-token: write
      contents: read

  update-third-party-api-sync-lambda:
    needs: third-party-api-sync-image

    uses: ./.github/workflows/update-lambda.yaml
    with:
      aws_account_id: "015059194123"
      aws_region: "us-east-1"
      image_tag: "third-party-sync"
      lambda_function_name: "stocks_third_party_api"

    permissions:
      id-token: write
      contents: read
